[project]
name = "shared-expenses-tracker"
revision = "1.0"

[profiles.development]
DATABASE_URL = { description = "DATABASE_URL secret", default = "file:local.db" }
GOOGLE_CLIENT_ID = { description = "GOOGLE_CLIENT_ID secret", required = true }
GOOGLE_CLIENT_SECRET = { description = "GOOGLE_CLIENT_SECRET secret", required = true }
OLLAMA_API_KEY = { description = "OLLAMA API key", required = false }
